const { src, dest } = require("gulp");

const htmlmin = require("gulp-htmlmin");
const inlinecss = require("gulp-inline-css");

const { dirname } = require("path");

const inline = (done) => {
  console.log("GULP TASK");
  src(`${dirname(require.main.filename)}/emails-files/*.html`)
    .pipe(
      inlinecss({
        applyStyleTags: true,
        applyLinkTags: true,
        removeStyleTags: true,
        removeLinkTags: true,
        preserveMediaQueries: true,
      })
    )
    .pipe(
      htmlmin({
        collapseWhitespace: true,
        // ignoreCustomFragments: [ /%%/],
        caseSensitive: true,
        continueOnParseError: true,
        html5: true,
        includeAutoGeneratedTags: false,
        // minifyCSS : true,
        removeComments: true,
      })
    )
    .pipe(
      dest(`${__dirname}/built-files/`).on("finish", () => {
        console.log("FINISHED INLINE");
        done();
      })
    );
  // done();
};

exports.buildFiles = inline;
